name: Terraform

inputs:
  src_directory:
    required: true
    type: string
    description: "Source directory to run terraform"

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      shell: bash
      working-directory: ${{ inputs.src_directory }}
    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.src_directory }}
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
      working-directory: ${{ inputs.src_directory }}
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      shell: bash
      working-directory: ${{ inputs.src_directory }}