name: 'Azure Infra Build'
on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

inputs:
  environment:
    description: Which environment is being deployed to
    type: choice
    default: non-prod
    options:
      - non-prod
      - prod

jobs:
  terrascan:
    name: 'Terrascan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: 'Terrascan'
        uses: './.github/actions/terrascan'
        with:
          iac_dir: 'src'

  # terratest:
  #   name: 'Unit Test'
  #   uses: './.github/templates/terratest'
  #   secrets: inherit
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    # needs: [terrascan, terratest]
    # permissions:
    #   pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Terraform
      #   uses: './.github/templates/terraform'
      #   secrets: inherit
      #   with:
      #     run_apply: false